#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")"

method=stack
if [ -e BUILD_WITH_NIX ]; then
	method=nix
fi

exe="xmonad-$(uname -m)-linux"
flakeAttr=xmonad-configuration
nixOut=result-build
DEST=
case ${1-} in
	''|--*) : ;;
	*) DEST=$(realpath -ms "$1"); shift ;;
esac

success() {
	res=$(realpath -e "$1")
	bar=$(realpath -e "$2")
	echo "Build success: $res $bar"
	for dst in "$DEST" "${XDG_CACHE_HOME:-"$HOME"/.cache}/xmonad/$exe" "${XDG_DATA_HOME:-"$HOME"/.local/share}/xmonad/$exe"; do
		[ -n "$dst" ] || continue
		dir="$(dirname "$(realpath -ms "$dst")")" || continue
		if ! [ -e "$dir" ]; then
			mkdir -p "$dir" || continue
		fi
		echo "Installing as $dst"
		ln -vnsf "$res" "$dst" || :
		ln -vnsf "$bar" "${dst%/*}/xmobar-run" || :
		#ln -vnsf "${res%/*}/xmobar-run" "${dst%/*}/xmobar-run" || :
	done
}

failure() {
	ret=$1
	case $ret in
		6 )
			echo "Failed to get lock on $(realpath .). Build already running probably. Waiting 5 minutes for it to finish."
			flock --verbose -w 300 . sleep 0.3
			echo "Build finished."
			;;
		* )
			echo "Build failed."
			exit "$ret"
			;;
	esac
}

case $method in
	nix )
		if flock -n -E 6 . nix -vL --log-format raw build ".#$flakeAttr" -o "$nixOut"; then
			success "$nixOut/bin/"{"$exe",xmobar-run}
		else
			failure "$?"
		fi
		;;
	stack )
		if flock -n -E 6 . stack build --no-haddock --no-haddock-deps; then
			success "$(stack path --dist-dir)/build/"{"$exe/$exe","xmobar-run/xmobar-run"}
		else
			failure "$?"
		fi
		;;
	* )
		exit 2
		;;
esac
