#!/bin/sh -e

cd "$(dirname "$0")" || exit 1

#if [ -t 1 ]; then
#	: "${VERBOSITY:=info}"
#fi
#: "${STACK_YAML:=stack.yaml}"
#: "${VERBOSITY:=warn}"  # silent, error, warn, info, debug
#: "${FAST:=}"           # set non-empty for faster builds
#: "${WITH_LLVM:=}"      # set non-empty to use LLVM

#pkg="xmonad-configuration"
bin="${XDG_DATA_HOME:-"$HOME"/.local/share}/xmonad"
exe="xmonad-$(uname -m)-linux"

case $1 in
	''|--*) : ;;
	*)
		bin=$(dirname "$(realpath -ms "$1")")
		exe=$(basename "$1")
		shift
		;;
esac

echo "Building: $bin/$exe"

# Nix build
attr=xmonad-x86_64-linux
#nix-build -A stack-nix.passthru.updateMaterialized | bash
nix-build -A "$attr" -o "$attr"
ln -nsf "$(realpath -e "$attr/bin/xmonad-x86_64-linux")" "$bin/$exe"
ln -nsf "$(realpath -e "$attr/bin/xmonad-x86_64-linux")" ~/.cache/xmonad/"$exe"

# Stack build
#if ! [ -e "$STACK_YAML" ]; then
#	STACK_YAML=$(find . -maxdepth 1 -type f -name stack-\*.yaml -print -quit)
#fi
#
#set -x
#
#"${STACK_EXE-stack}" --no-terminal --color never --verbosity "$VERBOSITY" --install-ghc --local-bin-path "$bin" \
#	build --copy-bins --no-haddock --flag "$pkg:${FAST:+-}optimize" ${FAST:+--fast} --flag "$pkg:${WITH_LLVM:+-}via-llvm" "$pkg:exe:$exe" "$@"
