#!/usr/bin/env bash
set -eou pipefail

target='xmonad-configuration:lib'
ghcOpts=''
ghciFlags='-fno-code -ferror-spans -fdiagnostics-color=always -Wno-prepositive-qualified-module'
stackGhciArgs="--ghci-options='$ghciFlags' --ghc-options='$ghcOpts' --no-load"

if [[ -n ${IN_NIX_SHELL-} ]]; then
	#com="command ghci $target $ghciFlags"
	com="cabal repl"
else
	com="stack ghci $target $stackGhciArgs"
fi
#STACK+=" --silent"

ghcid --command="$com" \
	--restart=./package.yaml --restart=./stack.yaml --restart="$0" \
	--clear --no-height-limit --reverse-errors "$@"
