---
name: xmonad-configuration
version: 0.17
synopsis: XMonad custumization

flags:
  optimize:
    description: Enable optimizations and LLVM
    default: false
    manual: true

library:
  source-dirs: lib

executables:
  xmonad-x86_64-linux:
    main: xmonad.hs
    dependencies: xmonad-configuration
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-N2 -G3 -c -qg1 -qn2 -M500M -A16M -K200M -kc8K -I0 -V0"'

dependencies:
  - base
  - containers
  - dbus
  - directory
  - free
  - process
  - multimap
  - text
  - unix
  - utf8-string
  - X11
  - filepath
  - xmobar         >= 0.36
  - xmonad         >= 0.15
  - xmonad-contrib >= 0.16
  - xdg-desktop-entry
  - random

ghc-options:
  - -dynamic
  - -pie
  - -fPIC

when:
  - condition: flag(optimize)
    ghc-options:
      - -O2
      - -fllvm
      - -fexpose-all-unfoldings
      - -fspecialise-aggressively
      - -fstatic-argument-transformation
      - -funbox-strict-fields
