---
spec-version: 0.36.0

name: xmonad-configuration
version: 0.18
synopsis: My XMonad configuration
description: |
  XMonad configuration with lots of custom things.
category: System
license: BSD3
author: Samuli Thomasson
maintainer: samuli.thomasson@pm.me
github: SimSaladin/xmonad-configuration
data-files: xmonad.svg
extra-doc-files: README.md
extra-source-files:
  - "*.nix"
  - "stack.yaml*"
  - build

flags:
  optimize:
    description: Enable optimizations
    default: false
    manual: true
  via-llvm:
    description: Compile via LLVM
    default: false
    manual: true

library:
  source-dirs: lib
  generated-other-modules: Paths_xmonad_configuration

executables:
  xmonad-x86_64-linux:
    main: xmonad.hs
    generated-other-modules: Paths_xmonad_configuration
    dependencies: xmonad-configuration
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-maxN4 -qn2 -A8M -K64M -M1G -kc8k"'
    when:
      - condition: flag(via-llvm)
        ghc-options: -fllvm
  xmobar-run:
    main: xmobar-run.hs
    dependencies: xmonad-configuration
    ghc-options:
      - -threaded
      - -rtsopts
      - '"-with-rtsopts=-maxN4 -qn2 -A8M -K64M -M1G -kc8k"'
    when:
      - condition: flag(via-llvm)
        ghc-options: -fllvm

dependencies:
  - base
  - containers
  - dbus >= 1.2.24
  - directory
  - free
  - process
  - multimap
  - text
  - unix
  - utf8-string
  - X11
  - filepath
  - xmobar         >= 0.36
  - xmonad         >= 0.17
  - xmonad-contrib >= 0.17
  - xdg-desktop-entry
  - random
  - rawfilepath

ghc-options:
  - -pie
  - -fPIC

when:
  - condition: flag(optimize)
    then:
      ghc-options:
        - -O2
        - -funbox-strict-fields
    else:
      ghc-options: -O0
