---
name: xmonad-configuration
version: 0.17
synopsis: My XMonad configuration
description: |
  XMonad configuration with lots of custom things.
category: System
license: BSD3
author: Samuli Thomasson
maintainer: samuli.thomasson@pm.me
github: SimSaladin/xmonad-configuration
data-files: xmonad.svg
extra-doc-files: README.md
#extra-source-files:

flags:
  optimize:
    description: Enable optimizations
    default: false
    manual: true
  via-llvm:
    description: Compile via LLVM
    default: false
    manual: true

library:
  source-dirs: lib
  when:
  - condition: false
    other-modules: Paths_xmonad_configuration

executables:
  xmonad-x86_64-linux:
    main: xmonad.hs
    dependencies: xmonad-configuration
    ghc-options:
    - -threaded
    - -rtsopts
    - '"-with-rtsopts=-maxN4 -G3 -c -qg1 -qn2 -A8M -K64M -M1G -kc8k"'

dependencies:
- base
- containers
- dbus
- directory
- free
- process
- multimap
- text
- unix
- utf8-string
- X11
- filepath
- xmobar         >= 0.36
- xmonad         >= 0.17
- xmonad-contrib >= 0.17
- xdg-desktop-entry
- random

ghc-options:
- -dynamic
- -pie
- -fPIC

when:
- condition: flag(optimize)
  then:
    ghc-options:
      - -O2
      - -fexpose-all-unfoldings
      - -fspecialise-aggressively
      - -fstatic-argument-transformation
      - -funbox-strict-fields
  else:
    ghc-options: -O0
- condition: flag(via-llvm)
  ghc-options:
    - -fllvm
