---
resolver: lts-20.8
packages:
  - .

flags:
  xmobar:
    all_extensions: true
  xmonad-configuration:
    optimize: true
    #via-llvm: true

extra-deps:
  - git: https://github.com/xmonad/xmonad.git
    commit: cf4d6f31b1751318309ddcc1c5fd8aa71a6a453a
  #- ./xmonad
  #- ./xmonad-contrib
  - git: https://github.com/SimSaladin/xmonad-contrib.git
    commit: 46e752870c65e6e0e04691f2856e09fe211f633a
  # X11                                                                   |
  - git: https://github.com/xmonad/X11
    commit: 8a33c4ebe7d0a1be96073d8c019f1f3901bbf344 # master
  - xmobar-0.46 # (Released 1/2023)
  - iwlib-0.1.0 # Wanted by xmobar
  - netlink-1.1.1.0 # Wanted by xmobar
